name: mycoai
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1=cuda11.3_0
  - expat=2.2.10=h9c3ff4c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hef1e5e3_0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - icu=58.2=hf484d3e_1000
  - kaleido-core=0.2.1=h3644ca4_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.9.14=h74e7548_0
  - mathjax=2.7.7=ha770c72_3
  - ncurses=6.4=h6a678d5_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=23.0.1=py311h06a4308_0
  - plotly=5.14.0=py_0
  - python=3.11.0=h7a1cb2a_3
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - sentencepiece=0.1.99=py311hdb19cb5_0
  - setuptools=65.6.3=py311h06a4308_0
  - sqlite=3.41.1=h5eee18b_0
  - tenacity=8.0.1=py311h06a4308_1
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - annotated-types==0.5.0
      - astroid==3.0.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - charset-normalizer==3.1.0
      - cloudpickle==2.2.1
      - cmake==3.26.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - dill==0.3.7
      - filelock==3.10.2
      - flatbuffers==23.3.3
      - fonttools==4.39.2
      - gast==0.4.0
      - google-auth==2.16.2
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - gymnasium==0.27.1
      - gymnasium-notices==0.0.1
      - h5py==3.8.0
      - idna==3.4
      - isort==5.12.0
      - jax==0.4.6
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - keras==2.12.0
      - kiwisolver==1.4.4
      - libclang==15.0.6.1
      - lit==16.0.0
      - markdown==3.4.2
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mccabe==0.7.0
      - mpmath==1.3.0
      - networkx==3.0
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==1.5.3
      - pillow==9.4.0
      - platformdirs==3.11.0
      - protobuf==4.22.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pygame==2.1.3.dev8
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-version==0.0.2
      - pytorch-nlp==0.5.0
      - pytz==2022.7.1
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - six==1.16.0
      - sympy==1.11.1
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tomlkit==0.12.1
      - torch==2.0.0
      - torchaudio==2.0.1
      - torchvision==0.15.1
      - tqdm==4.65.0
      - triton==2.0.0
      - typing-extensions==4.8.0
      - urllib3==1.26.15
      - werkzeug==2.2.3
      - wrapt==1.14.1
